If you would like to launch sbt with a specific port number directly
playframework/play-java-starter-example pull request #67
Opened 2018-05-03 08:24 UTC by kevinobama

If you would like to launch sbt with a specific port number directly:
```
sbt "run 9005"
```

2018-05-03 09:19 UTC, cchantep requested changes

2018-05-03 09:19 UTC, cchantep commented on README.md
> +sbt "run 9005"
That's part of the Play documentation. I'm for duplicating.

2018-05-03 09:50 UTC, kevinobama commented on README.md
> +sbt "run 9005"
where is that? I only found it in stack overflow.

2018-05-03 09:59 UTC, cchantep commented on README.md
> +sbt "run 9005"
Anyway if thats not already in the Play main doc, that's there it should be added, not here, as not specific to this example and would be prone to duplication

2018-05-03 10:27 UTC, kevinobama commented on README.md
> +sbt "run 9005"
ok.

2018-05-28 15:50 UTC, marcospereira commented on README.md
> +sbt "run 9005"
It is documented here:

https://www.playframework.com/documentation/2.6.x/PlayConsole#Using-the-play-commands-directly

I little buried in our docs. I agree with @cchantep that we should make it better there.

2018-05-30 03:54 UTC, closed without merging